version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    command: ["mysqld", "--log-bin=mysql-bin", "--server-id=1"]
    
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
     - 27017:27017